# Homebrew cask for courier.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
cask "courier" do
  version "0.1.0"
  sha256 "90d81f01f7892dfcd82d717d80cb4077df92ace145537119640f096a91f54d47"

  url "https://github.com/qzmfranklin/homebrew-tap/releases/download/courier-0.1.0/Courier-macos.zip"
  name "Courier"
  desc "AI coding agent"
  homepage "https://github.com/qzmfranklin/homebrew-tap"

  app "Courier.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Courier.app"],
                   sudo: false
    system_command "/usr/bin/codesign",
                   args: ["--force", "--sign", "-", "#{appdir}/Courier.app"],
                   sudo: false
  end
end
