# Homebrew cask for courier.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
cask "courier" do
  version "0.1.6"
  sha256 "d870e514099a2c1710e8661222bf75baff0f9a582e32a3138e6292028b28c991"

  url "https://github.com/qzmfranklin/homebrew-tap/releases/download/courier-0.1.6/Courier-macos.tar.xz"
  name "Courier Desktop"
  desc "AI coding agent"
  homepage "https://github.com/qzmfranklin/homebrew-tap"

  app "Courier Desktop.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Courier Desktop.app"],
                   sudo: false
    system_command "/usr/bin/codesign",
                   args: ["--force", "--sign", "-", "#{appdir}/Courier Desktop.app"],
                   sudo: false
  end
end
