# Homebrew cask for courier.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
cask "courier" do
  version "0.1.5"
  sha256 "387b4874645284eb8db5af7fcd0f69de069d298a43e8dd4a459831994acd0a5e"

  url "https://github.com/qzmfranklin/homebrew-tap/releases/download/courier-0.1.5/Courier-macos.tar.xz"
  name "Courier Desktop"
  desc "AI coding agent"
  homepage "https://github.com/qzmfranklin/homebrew-tap"

  app "Courier Desktop.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Courier Desktop.app"],
                   sudo: false
    system_command "/usr/bin/codesign",
                   args: ["--force", "--sign", "-", "#{appdir}/Courier Desktop.app"],
                   sudo: false
  end
end
