# Homebrew cask for vype.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
cask "vype" do
  version "1.1.1"
  sha256 "8550fb8548fc55cd8e0e80f59f9333cb6ef0c2181351c9e69e13d64ab02a2096"

  url "https://github.com/qzmfranklin/homebrew-tap/releases/download/vype-1.1.1/Vype-macos.zip"
  name "Vype"
  desc "Voice-driven input method and dictation"
  homepage "https://github.com/qzmfranklin/homebrew-tap"

  app "Vype.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Vype.app"],
                   sudo: false
    system_command "/usr/bin/codesign",
                   args: ["--force", "--sign", "-", "#{appdir}/Vype.app"],
                   sudo: false
  end
end
