# Homebrew cask for vype.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
cask "vype" do
  version "1.1.1"
  sha256 "4042a8d8e3b6daed44dcd639a3fe1b189d28b1434bb3077dd16f116ca017e19c"

  url "https://github.com/qzmfranklin/homebrew-tap/releases/download/vype-1.1.1/Vype-macos.zip"
  name "Vype"
  desc "Voice-driven input method and dictation"
  homepage "https://github.com/qzmfranklin/homebrew-tap"

  app "Vype.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-cr", "#{appdir}/Vype.app"],
                   sudo: false
    system_command "/usr/bin/codesign",
                   args: ["--force", "--sign", "-", "#{appdir}/Vype.app"],
                   sudo: false
  end
end
