# Homebrew cask for vype.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
cask "vype" do
  version "1.1.1"
  sha256 "e4954262fd5cf93159b8b893c6bdb2cd164320f552f424530d1daf82029c9990"

  url "https://github.com/qzmfranklin/homebrew-tap/releases/download/vype-1.1.1/Vype-macos.zip"
  name "Vype"
  desc "Voice-driven input method and dictation"
  homepage "https://github.com/qzmfranklin/homebrew-tap"

  app "Vype.app"

  postflight_steps do
    run "/usr/bin/xattr",
        args: ["-cr", "{{appdir}}/Vype.app"]
    run "/usr/bin/codesign",
        args: ["--force", "--sign", "-", "{{appdir}}/Vype.app"]
  end
end
