# Homebrew formula for iap.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
class Iap < Formula
  desc "Identity-aware proxy CLI: dev pods, SSH, git, and model access"
  homepage "https://github.com/qzmfranklin/homebrew-tap"
  # Platform choice lives in the argument, not in an on_macos block:
  # brew does not allow `url`/`sha256` inside an on_system block.
  # macOS is one universal (arm64 + x86_64) binary, so it needs no arch split.
  url on_system_conditional(
    macos: "https://github.com/qzmfranklin/homebrew-tap/releases/download/iap-3.0.0/darwin.xz",
    linux: on_arch_conditional(
      arm:   "https://github.com/qzmfranklin/homebrew-tap/releases/download/iap-3.0.0/linux/arm64.xz",
      intel: "https://github.com/qzmfranklin/homebrew-tap/releases/download/iap-3.0.0/linux/amd64.xz",
    ),
  )
  version "3.0.0"
  sha256 on_system_conditional(
    macos: "3743b0798d315976bfe06fc1ec15b82b0895b7cd607017ede46ed390dc65189a",
    linux: on_arch_conditional(
      arm:   "1774309252352fdb9681f0c4ddf7211b425b3574e422fcd32cbb37a6ffcc6698",
      intel: "1853480ccfb8dd664dd937837b7aaf82cf6dcec08ca54266e51fef87ab9b579d",
    ),
  )
  license :cannot_represent

  def install
    # Warn about a stray /usr/local/bin/iap. This one CANNOT be removed from
    # here: it is outside HOMEBREW_PREFIX on Apple Silicon (where the prefix is
    # /opt/homebrew), so no Homebrew sandbox ever grants write access to it, and
    # it is typically root-owned besides. Naming the exact command is the most
    # the formula can honestly do.
    #
    # Skipped when it IS our own prefix (Intel Homebrew installs at /usr/local),
    # where that path is the keg link rather than a stray copy.
    legacy = Pathname.new("/usr/local/bin/iap")
    if legacy.exist? && !legacy.to_s.start_with?("#{HOMEBREW_PREFIX}/")
      opoo <<~WARNING
        Another iap exists at #{legacy} and may shadow this Homebrew install
        if it comes first on your PATH. Remove it with:
            sudo rm #{legacy}
      WARNING
    end

    bin.install "iap"

    # Ad-hoc codesign on macOS. This is INTENTIONAL and load-bearing, not a
    # workaround: the binary is unsigned, and macOS refuses to exec an unsigned
    # or stale-signed Mach-O. Writing the file also invalidates any prior
    # signature, so it must be re-signed after install.
    #
    # chmod first: Homebrew stages files read-only, and both xattr and codesign
    # need to WRITE to the binary (xattr fails with EACCES otherwise).
    if OS.mac?
      chmod 0755, bin/"iap"
      system "/usr/bin/xattr", "-cr", bin/"iap"
      system "/usr/bin/codesign", "--force", "--sign", "-", bin/"iap"
    end

    # `--print SHELL` writes the script to STDOUT and installs nothing; a
    # bare `iap complete` would edit the user's rc file, which a
    # formula must not do.
    #
    # generate_completions_from_executable appends the shell name as the
    # final argument and writes each script where brew expects it, so it
    # replaces one hand-rolled safe_popen_read per shell.
    generate_completions_from_executable(
      bin/"iap",
      "complete",
      "--print",
      shells: [:bash, :zsh],
    )
  end

  def post_install
    # Remove a foreign `iap` from Homebrew's bin and take over the link.
    #
    # The shell installer drops a REAL FILE at <prefix>/bin/iap. Homebrew refuses to
    # link over anything it does not own, so without this the keg installs, `brew
    # link` fails, and `iap version` keeps reporting the installer's old build.
    # Homebrew is the authority when both are present, so the foreign file loses.
    #
    # This must live in `post_install`, not `install`:
    #   - The `install` sandbox grants writes only under the Cellar
    #     (allow_write_cellar), so unlinking <prefix>/bin/iap there fails with EPERM.
    #   - The `post_install` sandbox additionally grants every keg link directory
    #     (bin, etc, include, lib, sbin, share, var) under HOMEBREW_PREFIX, so the
    #     write is permitted here.
    #   - `pre_install` is not a Homebrew hook at all; defining one is ignored.
    #
    # link(keg) has ALREADY run by this point (FormulaInstaller#finish links before
    # calling post_install), so it will have failed against the foreign file. That
    # is why this re-links explicitly afterwards rather than just deleting.
    #
    # Only a NON-symlink is removed: Homebrew's own links are symlinks into the
    # Cellar, so this can never delete a link brew itself placed.
    foreign = HOMEBREW_PREFIX/"bin/iap"
    if foreign.exist? && !foreign.symlink?
      opoo "Removing #{foreign} left by the shell installer so Homebrew can link its own."
      foreign.unlink
      # Re-link now that the obstruction is gone; the earlier link(keg) failed.
      #
      # Guarded: Keg#link raises AlreadyLinkedError when the linked-keg record
      # already exists, which happens if the earlier link got far enough to record
      # itself before hitting the foreign file. An unhandled raise here would abort
      # an otherwise successful install, so treat "already linked" as success and
      # only warn on a genuine failure.
      begin
        keg = Keg.new(prefix)
        keg.link(verbose: false) unless keg.linked?
      rescue Keg::AlreadyLinkedError
        # Nothing to do -- the keg is already linked.
      rescue Keg::LinkError => e
        opoo "Could not link iap automatically (#{e.message}). Run: brew link iap"
      end
    end
  end

  def caveats
    <<~EOS
      To sign in:
        iap login

      This install is managed by Homebrew, so upgrade it with:
        brew update && brew upgrade iap
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/iap version")
  end
end
