# Homebrew formula for oyyama.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
class Oyyama < Formula
  desc "Large language model runner, interoperable with ollama"
  homepage "https://github.com/qzmfranklin/homebrew-tap"
  version "v1-20260806-193000"
  license :cannot_represent

  on_macos do
    # One universal (arm64 + x86_64) binary, matching what is published.
    url "https://github.com/qzmfranklin/homebrew-tap/releases/download/oyyama-v1-20260806-193000/oyyama-darwin-universal.tar.xz"
    sha256 "7c335e8808c6c29c238b2a76db9aa30072a5ae24704830ddf6842041fc4babd2"
  end

  on_linux do
    on_intel do
      url "https://github.com/qzmfranklin/homebrew-tap/releases/download/oyyama-v1-20260806-193000/oyyama-linux-amd64.tar.xz"
      sha256 "56156d5e2b79dd9e98660536c948d2eb2fd0db2c9058c95f5b7dcc53ad779e9a"
    end
    on_arm do
      url "https://github.com/qzmfranklin/homebrew-tap/releases/download/oyyama-v1-20260806-193000/oyyama-linux-arm64.tar.xz"
      sha256 "ed66b80357db887e6559aff236ea5577a6b0ef986b69f65fb2ced2af3a4559f9"
    end
  end

  def install
    bin.install "oyyama"

    # Ad-hoc codesign on macOS. This is INTENTIONAL and load-bearing, not a
    # workaround: the binary is unsigned, and macOS refuses to exec an unsigned
    # or stale-signed Mach-O. Writing the file also invalidates any prior
    # signature, so it must be re-signed after install.
    #
    # chmod first: Homebrew stages files read-only, and both xattr and codesign
    # need to WRITE to the binary (xattr fails with EACCES otherwise).
    if OS.mac?
      chmod 0755, bin/"oyyama"
      system "/usr/bin/xattr", "-cr", bin/"oyyama"
      system "/usr/bin/codesign", "--force", "--sign", "-", bin/"oyyama"
    end
  end

  def caveats
    <<~EOS
      oyyama is interoperable with the community `ollama`: it reads the same model
      cache (OLLAMA_MODELS, ~/.ollama/models) and serves the same OpenAI-compatible
      API, so the two can coexist on one machine.

      Get started:
        oyyama pull qwen3:0.6b
        oyyama run qwen3:0.6b
    EOS
  end

  test do
    assert_match "Large language model runner", shell_output("#{bin}/oyyama --help")
  end
end
