# Homebrew formula for oyyama.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
class Oyyama < Formula
  desc "Large language model runner, interoperable with ollama"
  homepage "https://github.com/qzmfranklin/homebrew-tap"
  # Platform choice lives in the argument, not in an on_macos block:
  # brew does not allow `url`/`sha256` inside an on_system block.
  # macOS is one universal (arm64 + x86_64) binary, so it needs no arch split.
  url on_system_conditional(
    macos: "https://github.com/qzmfranklin/homebrew-tap/releases/download/oyyama-1-20260807-184202/oyyama-darwin-universal.tar.xz",
    linux: on_arch_conditional(
      arm:   "https://github.com/qzmfranklin/homebrew-tap/releases/download/oyyama-1-20260807-184202/oyyama-linux-arm64.tar.xz",
      intel: "https://github.com/qzmfranklin/homebrew-tap/releases/download/oyyama-1-20260807-184202/oyyama-linux-amd64.tar.xz",
    ),
  )
  version "1-20260807-184202"
  sha256 on_system_conditional(
    macos: "41fb6f8b80a31ed614571e9acc706490d35f6ac469fd8e26d57e293821d852e1",
    linux: on_arch_conditional(
      arm:   "c3d3d9031203d5646dbba492af8b731e75ef2ce66c3e0b323fbf763ab790e030",
      intel: "0d8eb55198ddb2845339ec6112f86eb48769f6e39e69915a1cca1d952f0351bd",
    ),
  )
  license :cannot_represent

  def install
    bin.install "oyyama"

    # Ad-hoc codesign on macOS. This is INTENTIONAL and load-bearing, not a
    # workaround: the binary is unsigned, and macOS refuses to exec an unsigned
    # or stale-signed Mach-O. Writing the file also invalidates any prior
    # signature, so it must be re-signed after install.
    #
    # chmod first: Homebrew stages files read-only, and both xattr and codesign
    # need to WRITE to the binary (xattr fails with EACCES otherwise).
    if OS.mac?
      chmod 0755, bin/"oyyama"
      system "/usr/bin/xattr", "-cr", bin/"oyyama"
      system "/usr/bin/codesign", "--force", "--sign", "-", bin/"oyyama"
    end
  end

  def caveats
    <<~EOS
      oyyama is interoperable with the community `ollama`: it reads the same model
      cache (OLLAMA_MODELS, ~/.ollama/models) and serves the same OpenAI-compatible
      API, so the two can coexist on one machine.

      Get started:
        oyyama pull qwen3:0.6b
        oyyama run qwen3:0.6b
    EOS
  end

  test do
    assert_match "Large language model runner", shell_output("#{bin}/oyyama --help")
  end
end
