# Homebrew formula for oyyama.
#
# GENERATED by //prod/publish/tap -- do not edit by hand;
# the next release overwrites this file.
class Oyyama < Formula
  desc "Large language model runner, interoperable with ollama"
  homepage "https://github.com/qzmfranklin/homebrew-tap"
  # Platform choice lives in the argument, not in an on_macos block:
  # brew does not allow `url`/`sha256` inside an on_system block.
  # macOS is one universal (arm64 + x86_64) binary, so it needs no arch split.
  url on_system_conditional(
    macos: "https://github.com/qzmfranklin/homebrew-tap/releases/download/oyyama-1-20260807-184202/oyyama-darwin-universal.tar.xz",
    linux: on_arch_conditional(
      arm:   "https://github.com/qzmfranklin/homebrew-tap/releases/download/oyyama-1-20260807-184202/oyyama-linux-arm64.tar.xz",
      intel: "https://github.com/qzmfranklin/homebrew-tap/releases/download/oyyama-1-20260807-184202/oyyama-linux-amd64.tar.xz",
    ),
  )
  version "1-20260807-184202"
  sha256 on_system_conditional(
    macos: "e009cfd21e2eb3c426de5204b62bc908918fa74f0e2be0a5c12772c48b68d15c",
    linux: on_arch_conditional(
      arm:   "4a6c0c724a12cf64dd9ea3be86e3eb077a0ccbcb192ec125d13d25861c3651f6",
      intel: "382230e1ab37c2175359d1e3c7f8ba60088e32604dc5c6a594854e628832ef6c",
    ),
  )
  license :cannot_represent

  def install
    bin.install "oyyama"

    # Ad-hoc codesign on macOS. This is INTENTIONAL and load-bearing, not a
    # workaround: the binary is unsigned, and macOS refuses to exec an unsigned
    # or stale-signed Mach-O. Writing the file also invalidates any prior
    # signature, so it must be re-signed after install.
    #
    # chmod first: Homebrew stages files read-only, and both xattr and codesign
    # need to WRITE to the binary (xattr fails with EACCES otherwise).
    if OS.mac?
      chmod 0755, bin/"oyyama"
      system "/usr/bin/xattr", "-cr", bin/"oyyama"
      system "/usr/bin/codesign", "--force", "--sign", "-", bin/"oyyama"
    end
  end

  def post_install
    linked = HOMEBREW_PREFIX/"bin/oyyama"
    if linked.exist? && !linked.symlink?
      opoo <<~EOS
        Replacing a non-Homebrew oyyama at #{linked}.
        That file was almost certainly left by the legacy install script.
        The Homebrew-managed oyyama is now the one on your PATH.
      EOS
      linked.unlink
    end

    # Idempotent, and also repairs the case where the legacy binary was
    # deleted by hand: brew never created the symlink, so the tool was
    # missing from PATH entirely.
    linked.make_relative_symlink(bin/"oyyama") unless linked.symlink?
  end


  def caveats
    <<~EOS
      oyyama is interoperable with the community `ollama`: it reads the same model
      cache (OLLAMA_MODELS, ~/.ollama/models) and serves the same OpenAI-compatible
      API, so the two can coexist on one machine.

      Get started:
        oyyama pull qwen3:0.6b
        oyyama run qwen3:0.6b
    EOS
  end

  test do
    assert_match "Large language model runner", shell_output("#{bin}/oyyama --help")
  end
end
